apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-0603-new 
  janus-idp.io/tekton: codegen-0603-new
  backstage.io/kubernetes-id: codegen-0603-new
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: codegen-0603-new
resources: 
- application-dev.yaml